### ISSUE TITLE
Storing keys from master

### ISSUE THREAD

**Issue by somecallmemike** [PaquitoSoft/memored#3]
Is it possible to store keys in the master and have child processes access the data?  I have a long running process I only want run as one instance, and in a multi-cpu server I would have that process running multiple times unnecessarily consuming resources.

**Comment by PaquitoSoft** [comment]
Hi @somecallmemike 
I'm not sure I understand your question.
The whole point of this module is to store info un master and have child processes access to it. When you store a key from a child process, that key gets stored in the master process and, when it's read, it's also read from the master process.
This is true if you're using nodejs _cluster_ module.

If you run different master processes, then this nodule is not an option because you will need some kind of ICP (Inter Process Protocol) channel to communicate between them.

Please, feel free to reopen this issue if this answer is not clear.

Thanks.
